- import_tasks: "{{ role_path }}/tasks/init.yml"
  tags:
    - always

- import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: run_setup
  tags:
    - setup-all
    - setup-goneb

- import_tasks: "{{ role_path }}/tasks/setup_goneb.yml"
  when: run_setup
  tags:
    - setup-all
    - setup-goneb
