matrix_goneb_enabled: false

matrix_goneb_base_path: "{{ matrix_base_data_path }}/goneb"

# there are currently no tagged images, but in the future this should be fixed on the current known-good image
matrix_goneb_docker_image: "docker.io/matrixdotorg/go-neb:latest"

matrix_goneb_container_expose_port: false
# port that the container should bind to
matrix_goneb_container_port: 4050
# URL which is publicly available and where (f.ex. from github) webhooks get sent to
matrix_goneb_container_public_url: "http://goneb.{{ matrix_domain }}"

matrix_goneb_config_file_url: "{{ matirx_goneb_base_path }}/config.yaml"

# no other type is currently supported!
matrix_goneb_db_type: "sqlite3"
matrix_goneb_db_url: "/data/go-neb.db?_busy_timeout=5000"

# Default Go-NEB configuration template, smaller version of go-neb's example config file.
# You can customize it by controlling the various variables inside it, for examples look on github:
# https://github.com/matrix-org/go-neb/blob/master/config.sample.yaml
#
# For a more advanced customization, you can extend the default (see `matrix_goneb_configuration_extension_yaml`)
# or completely replace this variable with your own template.
matrix_goneb_configuration_yaml: |
  clients:
    - UserID: "@goneb:{{ matrix_domain }}"
      AccessToken: "YOUR_ACCESS_TOKEN_HERE"
      HomeserverURL: "http://matrix-synapse:8008"
      Sync: true
      AutoJoinRooms: true
      DisplayName: "Go-NEB!"
    - UserID: "@another_goneb_bot:localhost:{{ matrix_domain }}"
      AccessToken: "NEXT_ACCESS_TOKEN_HERE"
      HomeserverURL: "http:/matrix-synapse:8008"
      # Sync may be false for services which only send events _to_ matrix but never need to listen to them
      Sync: false
      AutoJoinRooms: false
      DisplayName: "Go-NEB!, but a second one!"
  realms:
    - ID: "github_realm"
      Type: "github"
      Config: {}
  sessions:
    - SessionID: "your_github_session"
      RealmID: "github_realm"
      UserID: "@YOUR_USER_ID:localhost"
      Config:
        # Populate these fields by generating a "Personal Access Token" on github.com
        AccessToken: "YOUR_GITHUB_ACCESS_TOKEN"
        Scopes: "admin:org_hook,admin:repo_hook,repo,user"
  services:
    - ID: "giphy_service"
      Type: "giphy"
      UserID: "@goneb:localhost" # requires a Syncing client
      Config:
        api_key: "qwg4672vsuyfsfe"
        use_downsized: false
    - ID: "imgur_service"
      Type: "imgur"
      UserID: "@imgur:localhost" # requires a Syncing client
      Config:
        api_key: "AIzaSyA4FD39m9"
    - ID: "wikipedia_service"
      Type: "wikipedia"
      UserID: "@goneb:localhost" # requires a Syncing client
      Config:
    - ID: "rss_service"
      Type: "rssbot"
      UserID: "@another_goneb:localhost"
      Config:
        feeds:
          "http://lorem-rss.herokuapp.com/feed?unit=second&interval=60": rooms: ["!qmElAGdFYCHoCJuaNt:{{  matrix_domain }}"]

matrix_dimension_configuration_extension_yaml: |
  # Your custom YAML configuration for Go-NEB goes here.
  # This configuration extends the default starting configuration (`matrix_goneb_configuration_yaml`).
  #
  # You can override individual variables from the default configuration, or introduce new ones.
  # For usage examples, see https://github.com/matrix-org/go-neb/blob/master/config.sample.yaml
  #
  # If you need something more special, you can take full control by
  # completely redefining `matrix_goneb_configuration_yaml`.
  #


# Holds the final Go-NEB configuration (a combination of the default and its extension).
# You most likely don't need to touch this variable. Instead, see `matrix_goneb_configuration_extension_yaml`.
matrix_goneb_configuration: "{{ matrix_goneb_configuration_yaml|from_yaml|combine(matrix_goneb_configuration_extension, 
recursive=True) }}"


